/**
 * Client for the iGEM Gallery Worker API.
 *
 * This module replaces the old direct-to-Airtable calls. Vite inlines every
 * VITE_* variable into the bundle as a literal string, so a write token in the
 * frontend is a published write token. VITE_API_URL is just a public endpoint,
 * which is safe: the Airtable credential lives in the Worker.
 *
 * The admin secret is never a build-time variable either — it is typed by the
 * admin at runtime, held in sessionStorage, and verified inside the Worker.
 */

const API_URL = import.meta.env.VITE_API_URL;

const REQUEST_TIMEOUT_MS = 30_000;

/**
 * One request to the Worker, with the error handling every caller needs.
 *
 * @param {string} path e.g. '/submit'
 * @param {{method?: string, body?: unknown, adminSecret?: string, timeoutMs?: number}} [options]
 * @returns {Promise<any>} the parsed JSON body
 * @throws {Error} with a message suitable for showing to a user
 */
async function apiFetch(path, { method = 'GET', body, adminSecret, timeoutMs = REQUEST_TIMEOUT_MS } = {}) {
  if (!API_URL) {
    throw new Error(
      'The API URL is not configured. Set VITE_API_URL in .env (local) or in ' +
      'the GitHub Actions workflow (deployed), then rebuild.'
    );
  }

  const headers = {};
  if (body !== undefined) headers['Content-Type'] = 'application/json';
  if (adminSecret) headers['X-Admin-Secret'] = adminSecret;

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);

  let response;
  try {
    response = await fetch(`${API_URL.replace(/\/+$/, '')}${path}`, {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
      signal: controller.signal,
    });
  } catch (cause) {
    // fetch only rejects on network failure or abort — never on HTTP status.
    if (controller.signal.aborted) {
      throw new Error('The request timed out. Check your connection and try again.', { cause });
    }
    // A CORS rejection is indistinguishable from a dead host here, so name both.
    console.error('[api] network failure:', cause);
    throw new Error('Could not reach the server. Check your connection and try again.', { cause });
  } finally {
    clearTimeout(timer);
  }

  const payload = await response.json().catch(() => null);

  if (!response.ok) {
    // The Worker writes its `error` strings for humans, so surface them as-is.
    throw new Error(payload?.error ?? `Request failed (HTTP ${response.status}).`);
  }

  return payload;
}

/**
 * Create a submission. Files must already be uploaded to Cloudinary.
 *
 * The verification code is generated by the Worker, not here — a
 * browser-chosen code could be made to collide with another team's.
 *
 * @param {{teamName: string, email: string, instagram?: string,
 *          mainImageUrl: string, secondaryImageUrls: string[], rulesPdfUrl: string}} submission
 * @returns {Promise<{success: true, verificationCode: string, recordId: string}>}
 */
export function submitGame(submission) {
  return apiFetch('/submit', { method: 'POST', body: submission });
}

/**
 * Games with Status = Approved, newest first. Public — no emails, no codes.
 *
 * @returns {Promise<Array<{id: string, teamName: string, instagram: string|null,
 *   mainImageUrl: string, secondaryImageUrls: string[], rulesPdfUrl: string|null}>>}
 */
export async function fetchApprovedGames() {
  const payload = await apiFetch('/approved');
  return payload?.games ?? [];
}

/**
 * Every submission, for the admin dashboard.
 *
 * @param {string} adminSecret
 * @param {'Pending'|'Approved'|'Rejected'|null} [status] omit for all
 */
export async function fetchAdminSubmissions(adminSecret, status = null) {
  const query = status ? `?status=${encodeURIComponent(status)}` : '';
  const payload = await apiFetch(`/admin/submissions${query}`, { adminSecret });
  return payload?.submissions ?? [];
}

/**
 * Approve or reject a submission.
 *
 * @param {string} adminSecret
 * @param {string} recordId Airtable record id ("rec...")
 * @param {'Pending'|'Approved'|'Rejected'} status
 */
export function setSubmissionStatus(adminSecret, recordId, status) {
  return apiFetch('/admin/status', {
    method: 'POST',
    body: { recordId, status },
    adminSecret,
  });
}

/**
 * Check an admin secret by making the cheapest authenticated call available.
 * Used by the login screen so a wrong password fails immediately rather than
 * after the dashboard has already rendered.
 *
 * @returns {Promise<boolean>} true if accepted; throws on network/server errors
 */
export async function verifyAdminSecret(adminSecret) {
  try {
    await fetchAdminSubmissions(adminSecret, 'Approved');
    return true;
  } catch (error) {
    if (/invalid admin credentials/i.test(error.message)) return false;
    throw error;
  }
}
